data <- read.table("household_power_consumption.txt", header = T, na.strings = "?", sep = ";")
target <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
target <- cbind(target, TimeFmt = strptime(paste(target$Date, target$Time), "%d/%m/%Y %H:%M:%S"))
png(filename = "plot2.png", width=480, height=480)
with(target, plot(Global_active_power ~ TimeFmt, type="l", xlab="", ylab="Global Active Power (kilowatts)"))
dev.off()