data <- read.table("household_power_consumption.txt", header = T, na.strings = "?", sep = ";")
target <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
target <- cbind(target, TimeFmt = strptime(paste(target$Date, target$Time), "%d/%m/%Y %H:%M:%S"))
png(filename = "plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(target$Global_active_power ~ target$TimeFmt, ylab="Global Active Power", xlab="", type="l")
plot(target$Voltage ~ target$TimeFmt, ylab="Voltage", xlab="datetime", type="l")
plot(target$Sub_metering_1 ~ target$TimeFmt, col="black", ylab="Energy sub metering", xlab="", type="l")
lines(target$Sub_metering_2 ~ target$TimeFmt, col="red")
lines(target$Sub_metering_3 ~ target$TimeFmt, col="blue")
legend("topright", lty=1, bty="n", col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(target$Global_reactive_power ~ target$TimeFmt, ylab="Global_reactive_power", xlab="datetime", type="l")
dev.off()