data <- read.table("household_power_consumption.txt", header = T, na.strings = "?", sep = ";")
target <- subset(data, Date %in% c("1/2/2007", "2/2/2007"))
target <- cbind(target, TimeFmt = strptime(paste(target$Date, target$Time), "%d/%m/%Y %H:%M:%S"))
png(filename = "plot3.png", width = 480, height = 480)
with(target, {
  plot(Sub_metering_1 ~ TimeFmt, type="l", col="black", ylab="Energy sub metering", xlab="")
  lines(Sub_metering_2 ~ TimeFmt, type="l", col="red")
  lines(Sub_metering_3 ~ TimeFmt, type="l", col="blue")
  legend("topright", lty=1, col=c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
})
dev.off()